### ISSUE TITLE
ThinkPad E14 Gen 5 (27c6:550a)

### ISSUE THREAD

**Issue by redscorpse** [goodix-fp-linux-dev/libfprint#29]
Please, would it be possible to use fprint on Debian 12 with the new ThinPad E14 Gen 5? It uses the Goodix Fingerprint reader:

```
Bus 001 Device 002: ID 27c6:550a Shenzhen Goodix Technology Co.,Ltd. FingerPrint
```

It's currently on the unsupported list, but I would really appreciate if you could work on it.

**Comment by gi-yt** [comment]
I have this device and got it working with the official drivers from lenovo's site: https://aryak.me/blog/03-e14-linux.html#goodix-fingerprint

**Comment by redscorpse** [comment]
So much thanks really 🤗
